# Exploration Du Jeu De Données

Nous allons découvrir et comprendre les données en analysant leur structure et leurs caractéristiques principales.

# Toucher par Lina Ben Slama

### Chargement des données

In [ ]:
import pandas as pd
df=pd.read_csv('student_stress_dataset.csv')

### Dimension et les noms des colonnes du dataset

In [ ]:
df.shape

(100, 6)

Cette dataset est composée de 100 lignes et 6 colonnes

In [ ]:
df.columns

Index(['id', 'study_hours', 'sleep_hours', 'social_media_hours', 'exam_score',
       'stress_level'],
      dtype='str')

### Affichage des premières lignes

In [ ]:
df.head()

   id  study_hours  sleep_hours  social_media_hours  exam_score stress_level
0   1            2            6                   5          55         High
1   2            5            7                   2          75          Low
2   3            1            5                   6          45         High
3   4            4            6                   3          70       Medium
4   5            6            8                   1          85          Low

### Affichage des dernières lignes

In [ ]:
df.tail()

     id  study_hours  sleep_hours  social_media_hours  exam_score stress_level
95   96            3            6                   4          62       Medium
96   97            2            5                   6          49         High
97   98            6            8                   1          89          Low
98   99            4            6                   3          66       Medium
99  100            1            5                   7          41         High

### Types des variables

In [ ]:
df.dtypes

id                    int64
study_hours           int64
sleep_hours           int64
social_media_hours    int64
exam_score            int64
stress_level            str
dtype: object

### Les informations générales du dataset

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  100 non-null    int64
 1   study_hours         100 non-null    int64
 2   sleep_hours         100 non-null    int64
 3   social_media_hours  100 non-null    int64
 4   exam_score          100 non-null    int64
 5   stress_level        100 non-null    str
dtypes: int64(5), str(1)
memory usage: 5.2 KB

### Les Statistiques Descriptives

In [ ]:
df.describe()

               id  study_hours  sleep_hours  social_media_hours  exam_score
count  100.000000   100.000000   100.000000          100.000000  100.000000
mean    50.500000     3.500000     6.080000            3.830000   64.350000
std     29.011492     1.743675     1.177911            2.098845   16.481624
min      1.000000     1.000000     4.000000            1.000000   39.000000
25%     25.750000     2.000000     5.000000            2.000000   48.000000
50%     50.500000     3.500000     6.000000            3.500000   64.500000
75%     75.250000     5.000000     7.000000            6.000000   79.250000
max    100.000000     7.000000     8.000000            7.000000   90.000000

In [ ]:
df.describe(include='object')

C:\Users\Lina Ben Slama\AppData\Local\Temp\ipykernel_28748\87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

       stress_level
count           100
unique            3
top            High
freq             34

### Détection et Traitement des doublons
Nombres des doublons

In [ ]:
df.duplicated().sum()

np.int64(0)

Suppression des doublons

In [ ]:
df=df.drop_duplicates()

     id  study_hours  sleep_hours  social_media_hours  exam_score stress_level
0     1            2            6                   5          55         High
1     2            5            7                   2          75          Low
2     3            1            5                   6          45         High
3     4            4            6                   3          70       Medium
4     5            6            8                   1          85          Low
..  ...          ...          ...                 ...         ...          ...
95   96            3            6                   4          62       Medium
96   97            2            5                   6          49         High
97   98            6            8                   1          89          Low
98   99            4            6                   3          66       Medium
99  100            1            5                   7          41         High

[100 rows x 6 columns]
<class 'pandas.DataFrame'>

### Gestion des valeurs manquantes
Nombre de valeurs manquantes par colonne

In [ ]:
df.isnull().sum()

id                    0
study_hours           0
sleep_hours           0
social_media_hours    0
exam_score            0
stress_level          0
dtype: int64

### Filtrage simple du jeu de données
Les étudiants qui révisent beaucoup (6 heures ou plus)

In [ ]:
df[df['study_hours'] >= 6]

    id  study_hours  sleep_hours  social_media_hours  exam_score stress_level
4    5            6            8                   1          85          Low
7    8            7            7                   2          90          Low
13  14            6            8                   1          88          Low
19  20            6            8                   1          89          Low
25  26            6            8                   1          87          Low
31  32            6            8                   1          90          Low
37  38            6            8                   1          86          Low
43  44            6            8                   1          88          Low
49  50            6            8                   1          89          Low
55  56            6            8                   1          87          Low
61  62            6            8                   1          90          Low
67  68            6            8                   1          88          Low
73  74            6            8                   1          89          Low
79  80            6            8                   1          87          Low
85  86            6            8                   1          90          Low
91  92            6            8                   1          88          Low
97  98            6            8                   1          89          Low

Les étudiants qui sont très stressés

In [ ]:
df[df['stress_level'] == 'High']

     id  study_hours  sleep_hours  social_media_hours  exam_score stress_level
0     1            2            6                   5          55         High
2     3            1            5                   6          45         High
6     7            2            5                   5          50         High
9    10            1            4                   7          40         High
12   13            2            5                   6          48         High
15   16            1            5                   7          42         High
18   19            2            5                   6          47         High
21   22            1            4                   7          41         High
24   25            2            5                   6          49         High
27   28            1            5                   7          43         High
30   31            2            5                   6          46         High
33   34            1            4                   7          39         High
36   37            2            5                   6          48         High
39   40            1            5                   7          44         High
42   43            2            5                   6          47         High
45   46            1            4                   7          42         High
48   49            2            5                   6          49         High
51   52            1            5                   7          41         High
54   55            2            5                   6          48         High
57   58            1            4                   7          40         High
60   61            2            5                   6          46         High
63   64            1            5                   7          43         High
66   67            2            5                   6          47         High
69   70            1            4                   7          42         High
72   73            2            5                   6          49         High
75   76            1            5                   7          41         High
78   79            2            5                   6          48         High
81   82            1            4                   7          40         High
84   85            2            5                   6          46         High
87   88            1            5                   7          43         High
90   91            2            5                   6          47         High
93   94            1            4                   7          42         High
96   97            2            5                   6          49         High
99  100            1            5                   7          41         High

### Filtrage avec conditions multiples

Les étudiants qui ont des mauvaises notes ET le stress élevé

In [ ]:
df[(df['exam_score']<50) & (df['stress_level'] == 'High')]

     id  study_hours  sleep_hours  social_media_hours  exam_score stress_level
2     3            1            5                   6          45         High
9    10            1            4                   7          40         High
12   13            2            5                   6          48         High
15   16            1            5                   7          42         High
18   19            2            5                   6          47         High
21   22            1            4                   7          41         High
24   25            2            5                   6          49         High
27   28            1            5                   7          43         High
30   31            2            5                   6          46         High
33   34            1            4                   7          39         High
36   37            2            5                   6          48         High
39   40            1            5                   7          44         High
42   43            2            5                   6          47         High
45   46            1            4                   7          42         High
48   49            2            5                   6          49         High
51   52            1            5                   7          41         High
54   55            2            5                   6          48         High
57   58            1            4                   7          40         High
60   61            2            5                   6          46         High
63   64            1            5                   7          43         High
66   67            2            5                   6          47         High
69   70            1            4                   7          42         High
72   73            2            5                   6          49         High
75   76            1            5                   7          41         High
78   79            2            5                   6          48         High
81   82            1            4                   7          40         High
84   85            2            5                   6          46         High
87   88            1            5                   7          43         High
90   91            2            5                   6          47         High
93   94            1            4                   7          42         High
96   97            2            5                   6          49         High
99  100            1            5                   7          41         High

Top étudiants (peu de stress + bonnes notes)

In [ ]:
df[(df['stress_level'] == 'Low') & (df['exam_score'] > 75)]

    id  study_hours  sleep_hours  social_media_hours  exam_score stress_level
4    5            6            8                   1          85          Low
7    8            7            7                   2          90          Low
10  11            5            7                   2          78          Low
13  14            6            8                   1          88          Low
16  17            5            7                   2          80          Low
19  20            6            8                   1          89          Low
22  23            5            7                   2          79          Low
25  26            6            8                   1          87          Low
28  29            5            7                   2          81          Low
31  32            6            8                   1          90          Low
34  35            5            7                   2          77          Low
37  38            6            8                   1          86          Low
40  41            5            7                   2          82          Low
43  44            6            8                   1          88          Low
46  47            5            7                   2          80          Low
49  50            6            8                   1          89          Low
52  53            5            7                   2          78          Low
55  56            6            8                   1          87          Low
58  59            5            7                   2          79          Low
61  62            6            8                   1          90          Low
64  65            5            7                   2          81          Low
67  68            6            8                   1          88          Low
70  71            5            7                   2          80          Low
73  74            6            8                   1          89          Low
76  77            5            7                   2          78          Low
79  80            6            8                   1          87          Low
82  83            5            7                   2          79          Low
85  86            6            8                   1          90          Low
88  89            5            7                   2          81          Low
91  92            6            8                   1          88          Low
94  95            5            7                   2          80          Low
97  98            6            8                   1          89          Low

Les étudiants qui utilisent beaucoup les réseaux sociaux OU manquent de sommeil

In [ ]:
df[(df['social_media_hours'] > 4) | (df['sleep_hours'] < 6)]

     id  study_hours  sleep_hours  social_media_hours  exam_score stress_level
0     1            2            6                   5          55         High
2     3            1            5                   6          45         High
6     7            2            5                   5          50         High
9    10            1            4                   7          40         High
12   13            2            5                   6          48         High
15   16            1            5                   7          42         High
18   19            2            5                   6          47         High
21   22            1            4                   7          41         High
24   25            2            5                   6          49         High
27   28            1            5                   7          43         High
30   31            2            5                   6          46         High
33   34            1            4                   7          39         High
36   37            2            5                   6          48         High
39   40            1            5                   7          44         High
42   43            2            5                   6          47         High
45   46            1            4                   7          42         High
48   49            2            5                   6          49         High
51   52            1            5                   7          41         High
54   55            2            5                   6          48         High
57   58            1            4                   7          40         High
60   61            2            5                   6          46         High
63   64            1            5                   7          43         High
66   67            2            5                   6          47         High
69   70            1            4                   7          42         High
72   73            2            5                   6          49         High
75   76            1            5                   7          41         High
78   79            2            5                   6          48         High
81   82            1            4                   7          40         High
84   85            2            5                   6          46         High
87   88            1            5                   7          43         High
90   91            2            5                   6          47         High
93   94            1            4                   7          42         High
96   97            2            5                   6          49         High
99  100            1            5                   7          41         High

### Filtrage par catégorie

Les étudiants qui ont 7 ou 8 heures de sommeil

In [ ]:
df [df['sleep_hours'].isin([7, 8])]

    id  study_hours  sleep_hours  social_media_hours  exam_score stress_level
1    2            5            7                   2          75          Low
4    5            6            8                   1          85          Low
7    8            7            7                   2          90          Low
10  11            5            7                   2          78          Low
13  14            6            8                   1          88          Low
16  17            5            7                   2          80          Low
19  20            6            8                   1          89          Low
22  23            5            7                   2          79          Low
25  26            6            8                   1          87          Low
28  29            5            7                   2          81          Low
31  32            6            8                   1          90          Low
34  35            5            7                   2          77          Low
37  38            6            8                   1          86          Low
40  41            5            7                   2          82          Low
43  44            6            8                   1          88          Low
46  47            5            7                   2          80          Low
49  50            6            8                   1          89          Low
52  53            5            7                   2          78          Low
55  56            6            8                   1          87          Low
58  59            5            7                   2          79          Low
61  62            6            8                   1          90          Low
64  65            5            7                   2          81          Low
67  68            6            8                   1          88          Low
70  71            5            7                   2          80          Low
73  74            6            8                   1          89          Low
76  77            5            7                   2          78          Low
79  80            6            8                   1          87          Low
82  83            5            7                   2          79          Low
85  86            6            8                   1          90          Low
88  89            5            7                   2          81          Low
91  92            6            8                   1          88          Low
94  95            5            7                   2          80          Low
97  98            6            8                   1          89          Low

### Tri des données

Tri décroissant par notes (Top 5 étudiants)

In [ ]:
df.sort_values(by='exam_score', ascending=False).head()

    id  study_hours  sleep_hours  social_media_hours  exam_score stress_level
31  32            6            8                   1          90          Low
7    8            7            7                   2          90          Low
85  86            6            8                   1          90          Low
61  62            6            8                   1          90          Low
49  50            6            8                   1          89          Low

Tri croissant par heures de réseaux sociaux + niveau de stress

In [ ]:
df.sort_values(by=['social_media_hours','stress_level'], ascending=[True, True])

     id  study_hours  sleep_hours  social_media_hours  exam_score stress_level
4     5            6            8                   1          85          Low
13   14            6            8                   1          88          Low
19   20            6            8                   1          89          Low
25   26            6            8                   1          87          Low
31   32            6            8                   1          90          Low
..  ...          ...          ...                 ...         ...          ...
75   76            1            5                   7          41         High
81   82            1            4                   7          40         High
87   88            1            5                   7          43         High
93   94            1            4                   7          42         High
99  100            1            5                   7          41         High

[100 rows x 6 columns]

Tri par niveau de stress et afficher les heures utilisées en réseaux sociaux, les notes et niveau de stress

In [ ]:
df[['social_media_hours', 'exam_score', 'stress_level']].sort_values(by=['stress_level'])

    social_media_hours  exam_score stress_level
0                    5          55         High
2                    6          45         High
6                    5          50         High
9                    7          40         High
12                   6          48         High
..                 ...         ...          ...
86                   3          69       Medium
89                   4          63       Medium
92                   3          68       Medium
95                   4          62       Medium
98                   3          66       Medium

[100 rows x 3 columns]

### Distribution des niveaux de stress

In [ ]:
df['stress_level'].value_counts() #répartition du stress

stress_level
High      34
Low       33
Medium    33
Name: count, dtype: int64

### Distribution des niveaux de stress en pourcentage

In [ ]:
df['stress_level'].value_counts(normalize=True)

stress_level
High      0.34
Low       0.33
Medium    0.33
Name: proportion, dtype: float64

### Moyenne des notes des étudiants par nombre d'heures d'études

In [ ]:
df.groupby('study_hours')['exam_score'].mean()

study_hours
1    41.705882
2    48.176471
3    62.187500
4    67.294118
5    79.250000
6    88.125000
7    90.000000
Name: exam_score, dtype: float64

### Moyenne des notes des étudiants par le niveau du stress

In [ ]:
df.groupby('stress_level')['exam_score'].mean()

stress_level
High      44.941176
Low       83.878788
Medium    64.818182
Name: exam_score, dtype: float64

### Moyenne des notes des étudiants par nombre d'heures de sommeil et de réseaux sociaux

In [ ]:
df.groupby(['sleep_hours', 'social_media_hours'])['exam_score'].mean()

sleep_hours  social_media_hours
4            7                     40.750000
5            5                     50.000000
             6                     47.437500
             7                     42.250000
6            3                     67.294118
             4                     62.187500
             5                     55.000000
7            2                     79.882353
8            1                     88.125000
Name: exam_score, dtype: float64

### Moyenne des notes des étudiants par heures de sommeil, heures de réseaux sociaux et niveau de stress

In [ ]:
df.groupby(['study_hours', 'sleep_hours', 'social_media_hours', 'stress_level'])['exam_score'].mean()

study_hours  sleep_hours  social_media_hours  stress_level
1            4            7                   High            40.750000
             5            6                   High            45.000000
                          7                   High            42.250000
2            5            5                   High            50.000000
                          6                   High            47.600000
             6            5                   High            55.000000
3            6            4                   Medium          62.187500
4            6            3                   Medium          67.294118
5            7            2                   Low             79.250000
6            8            1                   Low             88.125000
7            7            2                   Low             90.000000
Name: exam_score, dtype: float64